name: platform_design
description: A project showcasing a Flutter app following different platform IA conventions.
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  audioplayers:  ^0.10.0
  english_words: ^3.1.5
  flutter_lorem: ^1.1.0
  flutter:

    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
